### ISSUE TITLE
loading sxos'payload black screen

### ISSUE THREAD

**Issue by zerofo** [mattytrog/FUSEE_SUITE#1]
After loading sxos's payload into system(after the switch logo), Certain probability of black screen. it can't wakeup. 
rcm x86. use https://github.com/mattytrog/FUSEE_SUITE/blob/master/Fusee-Suite/Part_2_Version_6.110320/RCM_X86.UF2

but, https://github.com/euclala/RCM-X86/blob/master/TXOS/TXOS_internal.uf2 this work good.

**Comment by mattytrog** [comment]
Should be fixed. This is the USB logic IC on early RCM-X86. Pulled LOW to enable USB (ie on boot). Upon sleep, must go high. So enabled all of the time(in order to keep the G18 USB pins disconnected). Will close for now. Cannot replicate.
