### ISSUE TITLE
Seeeduino-XIAO support

### ISSUE THREAD

**Issue by Nobody4000** [mattytrog/FUSEE_SUITE#4]
Hey hope you are well.

This is not an issue, just a request.

Can you add suport for seeeduino xiao ?
https://wiki.seeedstudio.com/Seeeduino-XIAO/

With feather files, led is working ,functions asigned to pads not present on seeduino.
With m0/rebug/rcm x86 files - no led, dasn't seems to go to sleep.

Thank you.

**Comment by mattytrog** [comment]
Yes support coming later. Thank-you! Will keep open until I've completed support.

**Comment by mattytrog** [comment]
OK Diagrams and files for Seeeduino XIAO added. Hope the pinouts are suitable. I tried to get the straps best for routing (ie 7 = VOL+, 10 = JOYCON, 2 on opposite side for USB). I cannot test this as I do not own such a device. It has an external 32.768mhz external oscillator like the Feather. Please let me know how it goes!

**Comment by Nobody4000** [comment]
Everyting looks perfect, i can't test this anymore, but i will test a soon as i can(i need to fix a v1 mb to test again) for now i can only test with usb power from pc or from bench power supply, power draw go to about 0.012A and then sleep to 0.003A , with green led for power indication not removed yet, so sleep is fixed, led(orange) is working now like on feather files but it dasn't go off  like on trinket m0 or similar , to fix this probably i will just remove all 4 leds. Great job as always,thank you.

**Comment by mattytrog** [comment]
Ahhh yes. The tx and rx LEDs it has. Forgot about those. I'll add a fix to
turn them off. We don't need them. Thank you

**Comment by Nobody4000** [comment]
![xeduino](https://user-images.githubusercontent.com/107756203/176902444-2ff86ef5-4a32-4922-9c2b-7a8b50e15e4d.jpg)
Hey, the orange led is still on, again not big deal i can remove all leds when i will remove the green one(for power status) , maybe because of this note on xiao wiki page  "Please note: The behavior of the built-in LED is reversed to the one on an Arduino. On the Seeeduino Xiao, the pin has to be pulled low, whereas on other micro-controllers it has to be pulled high " ? Thank you.

**Comment by mattytrog** [comment]
Hey I didn't see your message. I'll take a look at the xiao schematics and
will put a fix out. Thank you!

**Comment by Nobody4000** [comment]
When you have time, in the meantime i managed to do a test as an external dongle and is working. I still don't have a personal working  v1 to do internal  test's. Thank you .

**Comment by mattytrog** [comment]
Hello there. Thanks for getting in touch. Yes I certainly can add support
for that. I'll create a part 1/board cfg etc etc a little later. Not take
long. Just off to daughters for her 21st birthday so will attack it a bit
later.

Thanks and have a good day
Matty
