### ISSUE TITLE
Differences in various install options and part 2 / settings files?

### ISSUE THREAD

**Issue by bobmarley2021** [mattytrog/FUSEE_SUITE#6]
Hi, 

I'm sorry if this doesn't really belong here (I don't have a GBAtemp account anyway) but I came across your amazing project whilst watching a YT video. So firstly, thanks for even doing this, because it's really cool. :) 

The install tutorial video is from a well known modder from the US that likes rock music and balaclavas. The video in question is about a year old so the files provided are quite out of date, although the wiring diagram appears to match what you have in your recent versions. I also got looking through some of the GBAtemp threads like this one: https://gbatemp.net/threads/trinket-m0-installed-inside-the-switch.508292/ and this one: https://gbatemp.net/threads/trinket-internal-install.509633/ and the points used are very different - I'm guessing these are prior to the addition of the Vol+ strap so should no longer be followed? 

Please excuse my ignorance but I just need to flash my trinket with PART_1_FUSEE_TRINKET-c40fc1c.uf2 then part 2 TRINKET.UF2? And the default settings are for all straps soldered? 

Thanks and sorry if this is really basic stuff.. I just don't want to remove the microusb then find out I flashed the wrong thing!

**Comment by mattytrog** [comment]
Hello... Right lets go through this. I haven't seen any install video. I didn't even realise many people used this!

You have a Trinket. So, your flashing routine should be:

Trinket Part 1 from the main Fusee_UF2 branch.
Trinket Part 2 from main Fusee_UF2 branch.
If fitting all straps, you can optionally flash a SETTINGS.UF2 to preset your chip for you(eg if you want dual-boot/permanent CFW/RCM or the new Failsafe RCM.

You don't "have" to flash a Settings UF2. It is assumed all straps are soldered, correct. The Settings UF2 is completely optional.

**Comment by bobmarley2021** [comment]
Brilliant thanks, that clears that up! :)

From what I can gather, this seems to be pretty popular.. not having to carry round / get out a jig and RCMloader is golden. I was actually looking for some info on the OLEDs when I came across it, and had originally planned to mod all my right joycons so I could drop the jig, but this is way better and scores massive tinker points :D

If you're interested in the video google "switch unpatched m0dchip install youtube" it's quite a long watch but seems to contain some good advice. I'm not a soldering novice but I haven't attempted anything like this before... I am patient and have a steady hand though so I've just ordered a new solder station, hot air station and digital microscope. I have 3 switch V1s so I thought why not?

Anyway, thanks once again for such a great project, keep up the good work and thanks for taking the time to reply.

**Comment by mattytrog** [comment]
You are very welcome. Glad it has been some use. Thank you for your kind
words. Keep checking back from time to time.

All the best
Matty

**Comment by ellnic** [comment]
@mattytrog +1 thanks for this. My wife taught herself how to to micro solder in 2 hours just so we could do this. I have soldering experience, but nothing on this scale. The Mrs has worked with very small jewellery and felt up to the task. After a couple of hours trialling it on a duff Erista V2, she took the plunge on one of our main units. I think she did well: https://ibb.co/Qdh6P8K

1 down, 3 to go :D

Sorry to hijack this issue, but what is USB voltage? Is that only applicable when USB power is attached or did we miss a strap somewhere?
